apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "learning-ingress-ipaddress"
    kubernetes.io/ingress.class: "gce"
spec:
  ingressClassName: "gce"
  rules:
    - host: quochuynguyen.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    # - host: grafana.quochuynguyen.tech
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: kube-prometheus-stack-grafana
    #             port:
    #               number: 80
