apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: loki
data:
  promtail.yaml: |
    server:
      http_addr: ":3100"

    positions:
      sources:
        "*": "/var/log/containers/*.log"
